package com.geekerstar.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table bs_city
 *
 * @mbg.generated do_not_delete_during_merge
 */
@ApiModel(value = "com.geekerstar.entity.BsCity")
public class BsCity implements Serializable {
    /**
     * Database Column Remarks:
     * ID主键
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_city.id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "idID主键")
    private String id;

    /**
     * Database Column Remarks:
     * 姓名
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_city.name
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "name姓名")
    private String name;

    /**
     * Database Column Remarks:
     * 创建时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_city.create_time
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "createTime创建时间")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_city
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_city.id
     *
     * @return the value of bs_city.id
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_city.id
     *
     * @param id the value for bs_city.id
     * @mbg.generated
     */
    public BsCity setId(String id) {
        this.id = id;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_city.name
     *
     * @return the value of bs_city.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_city.name
     *
     * @param name the value for bs_city.name
     * @mbg.generated
     */
    public BsCity setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_city.create_time
     *
     * @return the value of bs_city.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_city.create_time
     *
     * @param createTime the value for bs_city.create_time
     * @mbg.generated
     */
    public BsCity setCreateTime(Date createTime) {
        this.createTime = createTime;
        return this;
    }
}
